### ISSUE TITLE
ez_setup.py is very old

### ISSUE THREAD

**Issue by tristeng** [accumulo/pyaccumulo#23]
It installs a very old version of setup tools, and I think that setup.py should probably attempt to load setup tools functions before trying to import from ez_setup.py. In my virtual environment, it was installing the old version of setup tools over top of a much newer version of setup tools, and I was seeing some errors like "Failed building wheel..." for certain packages I was trying to install. 

Consider replacing this:
```python
try:
    from ez_setup import use_setuptools
    use_setuptools()
except ImportError:
    pass

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup
```

with this:
```python
try:
    from setuptools import setup, find_packages
except ImportError:
    from ez_setup import use_setuptools
    use_setuptools()
    from setuptools import setup, find_packages
```

I'm not a python setup.py expert, but the above change in my forked repository is working for me.

**Comment by johnrfrank** [comment]
Thanks for pointing that out.  I've fixed it in 1.5.0.9
